### ISSUE TITLE
GameObjectExtensions gives error since you have not included the TransformExtensions script

### ISSUE THREAD

**Issue by TahaAltindag** [adammyhre/Unity-Service-Locator#1]
Hello Adam,
I admire your effort and repos. 
You missed TransformExtensions script in [here](https://github.com/adammyhre/Unity-Utils/blob/master/UnityUtils/Scripts/Extensions/TransformExtensions.cs) in this repo so it GameObjectExtensions does not work properly. Hope you'll fix that.

**Comment by adammyhre** [comment]
Removed unused extension methods with dependencies.
